name: Elixir CI

on:
  pull_request:
  push:
    branches:
      - main

env:
  ELIXIR_VERSION: 1.14.4
  OTP_VERSION: 26.0
  MIX_ENV: test

jobs:
  deps:
    runs-on: ubuntu-latest
    outputs:
      deps-cache-key: ${{ steps.get-cache-key.outputs.key }}
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.OTP_VERSION }}
          elixir-version: ${{ env.ELIXIR_VERSION }}

      - id: get-cache-key
        run: echo "key=mix-${{ env.ELIXIR_VERSION }}-${{ env.OTP_VERSION }}-${{ hashFiles('**/mix.lock') }}" >> $GITHUB_OUTPUT

      - uses: actions/cache@v2
        id: cache-deps
        with:
          path: |
            deps
            _build
          key: ${{ steps.get-cache-key.outputs.key }}

      - run: mix do deps.get, deps.compile
        if: steps.cache-deps.outputs.cache-hit != 'true'

  credo:
    needs: deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.OTP_VERSION }}
          elixir-version: ${{ env.ELIXIR_VERSION }}

      - uses: actions/cache@v2
        id: cache-deps
        with:
          path: |
            deps
            _build
          key: ${{ needs.deps.outputs.deps-cache-key }}

      - run: mix credo

  format:
    needs: deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.OTP_VERSION }}
          elixir-version: ${{ env.ELIXIR_VERSION }}

      - run: mix format --check-formatted

  docs:
    needs: deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.OTP_VERSION }}
          elixir-version: ${{ env.ELIXIR_VERSION }}

      - uses: actions/cache@v2
        id: cache-deps
        with:
          path: |
            deps
            _build
          key: ${{ needs.deps.outputs.deps-cache-key }}

      - run: mix docs

  test:
    needs: deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.OTP_VERSION }}
          elixir-version: ${{ env.ELIXIR_VERSION }}

      - uses: actions/cache@v2
        id: cache-deps
        with:
          path: |
            deps
            _build
          key: ${{ needs.deps.outputs.deps-cache-key }}

      - run: mix test
